google/minja

- include/minja/minja.hpp
- tests/CMakeLists.txt
- tests/contexts/tool_use.json
- tests/test-syntax.cpp
https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407
> Support mistralai/Mistral-Nemo-Instruct-2407

- README.md
- include/minja/minja.hpp
- tests/test-syntax.cpp
https://jinja.palletsprojects.com/en/stable/templates/#id11
Needed for https://github.com/google/minja/issues/7
> Add support for filter...endfilter blocks

- include/minja/minja.hpp
- tests/test-syntax.cpp
*Almost* fixes https://github.com/google/minja/issues/7
This adds the following features:
Still some issues w/ `functions` and `datetime` expected in template (crashes jinja2), which get resolved to None if I add them in the context. Will do a follow up PR.
> Improve support for fireworks-ai/llama-3-firefunction-v2

- include/minja/minja.hpp
- tests/test-syntax.cpp
More work is needed, but here's already:
- argument list expansion `*`
- `int` filter
https://github.com/google/minja/issues/8
> Improve ai21labs/AI21-Jamba-1.5-Large support

- include/minja/chat-template.hpp
- include/minja/minja.hpp
- scripts/fetch_templates_and_goldens.py
- scripts/run_tests.sh
- tests/CMakeLists.txt
- Robust system message support detection
- Robust arguments-as-object detection
- Json fix in python expectations logic
> chat_template.hpp improvements

- include/minja/minja.hpp
- tests/CMakeLists.txt
Now that this model is run on CI (https://github.com/google/minja/pull/21), time to unskip it & promote previously commented-out fix.
Thanks @slaren! ([ref](https://github.com/ggerganov/llama.cpp/pull/11016#issuecomment-2599766199))
> Fix bofenghuang/vigogne-2-70b-chat on Windows

- include/minja/minja.hpp
Before calling them would either lead to an exception being thrown or a null pointer dereference.
> erase functions have bugs

- include/minja/minja.hpp
- tests/test-syntax.cpp
This is to support an exploration of user-configurable message normalization [using a template](https://gist.github.com/ochafik/a3870e95c3f07d57471b05eaf30917eb)
> List & object pop() method

- include/minja/minja.hpp
Allows dropping the normalize_newlines at end of TemplateNode::render
(the one in the parser is still needed to guard against \r )
cc/ @slaren ([ref](https://github.com/ggerganov/llama.cpp/pull/11016#discussion_r1922978235))
> Drop ENDL macro

- include/minja/minja.hpp
- tests/test-chat-template.cpp
Quick follow up to https://github.com/google/minja/pull/26
Parser needs to protect against \r\n by itself, can't just rely on caller (here, test) to pass \n delimited lines only
> Move normalize_newlines from test to parser

- include/minja/chat-template.hpp
- include/minja/minja.hpp
- scripts/fetch_templates_and_goldens.py
- tests/CMakeLists.txt
- tests/test-syntax.cpp
Fixes #28
- Parse `{% generation %}` blocks (no-op for inference)
- Accommodate models that require typed content (`"messages": {"role": "user", "content": [{"type": "text", "text": "Hey"}]}`)
> Support MiniMaxAI/MiniMax-Text-01

- include/minja/chat-template.hpp
- include/minja/minja.hpp
- scripts/fetch_templates_and_goldens.py
- tests/contexts/tool_use_code_interpreter.json
- tests/test-syntax.cpp
`rejectattr` is used in meetkai-functionary-medium-v3.1 (activated only when code_interpreter found in tools)
Also added support for arguments being a code string
Note: shared most of the code w/ existing selectattr + reject
> Support rejectattr + select

- include/minja/minja.hpp
- tests/test-syntax.cpp
Upcoming revamp of template feature detection relies heavily on error cases, which this aligns w/ Jinja for Nones in binary operations
> Explode on operations w/ Nones

- include/minja/minja.hpp
- tests/test-syntax.cpp
Causes issues in tool call support of llama.cpp, will need to think this more through
> Revert "Explode on operations w/ Nones"

- include/minja/minja.hpp
Everything seems to compile fine when this is const. It being non-const makes it hard to pass in a temporary (rvalue).
**edit:** ~~I intend to sign the CLA but it's going to take me some time to figure out the Google Groups stuff that I need.~~
> accept a const value ref in Context::set

- include/minja/minja.hpp
- tests/CMakeLists.txt
- tests/test-syntax.cpp
https://jinja.palletsprojects.com/en/stable/extensions/#loop-controls
Fixes https://github.com/google/minja/issues/38
> Support loop controls for CohereForAI/c4ai-command-r7b-12-2024

- include/minja/minja.hpp
https://github.com/ggerganov/llama.cpp/pull/11581
> Avoid ostringstream::str which breaks openEuler build on llama.cpp

- include/minja/minja.hpp
- tests/test-syntax.cpp
@ericcurtin sorry, finally got to look into it. Hopefully this does the trick, should be a simpler fix than https://github.com/google/minja/pull/37
> Fix multiline comments (. isn't multiline, need [\s\S\r\n])

- include/minja/chat-template.hpp
- scripts/fetch_templates_and_goldens.py
- tests/CMakeLists.txt
- tests/test-polyfills.cpp
Follow up to https://github.com/google/minja/pull/46
> Add test-polyfills

- include/minja/minja.hpp
- tests/test-syntax.cpp
Continuation of #37
Since c73b53f, minja hangs when parsing the template `{#`, e.g.:
```cpp
#include <minja/minja.hpp>
int main() {
try {
minja::Parser::parse("{#", {});
} catch (...) {
return 1;
}
}
```
This program should exit with status code 1, but instead it hangs.
I found a fix that works even with the nonconforming Microsoft STL, and added a test.
> Fix hang when parsing unclosed comment

- include/minja/chat-template.hpp
- scripts/fetch_templates_and_goldens.py
- tests/CMakeLists.txt
- tests/contexts/simple.json
- tests/contexts/system.json
- tests/contexts/tool_use.json
- tests/test-polyfills.cpp
- tests/test-supported-template.cpp
Also:
- add golden output tests for tool handling of common templates
- align python & c++ test logics (fix c++ extra context, fix python globals redefinitions, remove tojson override)
> Fix deepseek r1 tool call example polyfill (template newly adds trailing <think>)

- CMakeLists.txt
- README.md
- include/minja/chat-template.hpp
- include/minja/minja.hpp
The two simplest ways to get nlohmann/json are to install it system-wide, or to vendor it via CMake.
If you install it system-wide, it will be at `/usr/include/nlohmann/json.hpp` (on Arch Linux, at least). minja is not compatible with this out-of-the-box, requiring you to add the non-standard #include path of `-I/usr/include/nlohmann`.
This is confirmed by `/usr/share/pkgconfig/nlohmann_json.pc`, which does not list `/usr/include/nlohmann` as a required include directory:
```
Name: nlohmann_json
Description: JSON for Modern C++
Version: 3.11.3
Cflags: -I/usr/include
```
If you provide the json dependency as part of a CMake project like this:
```cmake
add_subdirectory(deps/json)  # or FetchContent_Declare/FetchContent_MakeAvailable
target_link_libraries(mytarget PRIVATE …
```
> Use the canonical #include location for json.hpp

- include/minja/minja.hpp
- tests/CMakeLists.txt
- tests/test-syntax.cpp
cc/ @CISC ([ref](https://github.com/ggml-org/llama.cpp/pull/12634#issuecomment-2763257852))
> Add `upper` filter (to support inclusionAI/Ling-Coder-lite)

- CMakeLists.txt
- README.md
- examples/CMakeLists.txt
- examples/chat-template.cpp
- examples/raw.cpp
- tests/CMakeLists.txt
- tests/test-capabilities.cpp
- tests/test-chat-template.cpp
- tests/test-fuzz.cpp
- tests/test-polyfills.cpp
- tests/test-supported-template.cpp
- tests/test-syntax.cpp
Functionality of the minja library works well, and I think it's a great library. But it lacks proper CMake packaging, which makes it difficult to integrate smoothly within other CMake-based projects.
This PR introduces the following changes:
1. Install Command
The `install` command has been added so that running running `make install` will let you put the header files into `$CMAKE_INSTALL_PREFIX/include/minja`.
2. FetchContent Integration
A CMake target has been defined to support users who want to include minja using `FetchContent`. This means other C++ projects to can import minja like this:
```cmake
FetchContent_Declare(minja URL "minja-url")
FetchContent_MakeAvailable(minja)
```
3. Optional Python Dependency
Currently, minja's CMake configuration requires a Python interpreter. For …
> make minja packagable by setting target in cmake

- include/minja/minja.hpp
- tests/test-syntax.cpp
As mentioned in #64, some operators in [Qwen3's template](https://huggingface.co/Qwen/Qwen3-4B/blob/main/tokenizer_config.json#L230) are not supported yet on latest minja.
#66 fixes most of them, but I found another problem during my tests on Qwen3.
I wanted to disable 'thinking' at all in Qwen3, by passing over `inputs.extra_context = {{"enable_thinking", "false"}};`, then I got `Unknown type for 'is' operator: false`.
So I needed to add `"false"` as possible name of rhs of `is` operator. (`"true"` must be one too, so added it too.)
After I applied these changes and #66, I finally succeeded to run templating for Qwen3's in my case.
Tests for these changes are also added.
> Add `true` and `false` as operands of `is` and `is not`

- include/minja/chat-template.hpp
In the latest document of transformers([link](https://huggingface.co/docs/transformers/v4.51.3/en/chat_templating_writing#tool-calls)), a message containing 'tool calls' contains member with key `"tool_calls"` instead of "content".
```json
{
"role": "assistant",
"tool_calls": [
{
"type": "function",
"function": {
"name": "multiply",
"arguments": {
"a": 5,
"b": 6
}
}
}
]
}
```
The 'tool call' messages are not necessarily included as input messages because they are model outputs rather than model inputs. However, they are necessary to provide context during the process of providing tool execution results or after.
Currently, a message without `"content"` cannot be put into `chat_template::apply()` due to the validation logic as follows. …
> Consider `"tool_calls"` instead of `"content"` in messages

- include/minja/chat-template.hpp
The `nullptr` cause `Test failed: basic_string: construction from null is not valid`.
The root cause is the ternary operator of `std::string` and `nullptr`
> Before C++23:
> Constructing a std::string from a null pointer (like nullptr or NULL) results in Undefined Behavior. This means the program's behavior is unpredictable and can lead to crashes or incorrect results.
> In C++23 and later:
> Constructing a std::string from a null pointer is explicitly disabled and will result in a compilation error. This prevents the undefined behavior from occurring.
https://softwareengineering.stackexchange.com/questions/450335/is-it-bad-practice-to-use-nullptr-in-ternary-operation
Change to use empty `json` `j_null` instead.
https://json.nlohmann.me/api/basic_json/is_null/
Tests pass with …
> Fix null content for chat-template.

- include/minja/minja.hpp
- scripts/fetch_templates_and_goldens.py
- tests/CMakeLists.txt
- tests/test-syntax.cpp
- Add `replace` method for string type and update unit tests.
- Support slice expression with omitted start or end index and update unit tests.
- Fix the bug that `in` operator does not work for string type.
- Update testing script to support fetching `chat-template.jinja` when the template is not in `tokenizer_config.json`.
Test passed with SmolLM 3B model:
https://huggingface.co/HuggingFaceTB/SmolLM3-3B
> Enable SmolLM 3 template.

- include/minja/chat-template.hpp
- tests/CMakeLists.txt
- tests/test-capabilities.cpp
Problems in that template came from the detection of whether content needs to be non-null, which needs to add more messages when the logic only triggers in some loop iterations.
```c++
{%- for message in messages %}
{%- if (message.role == "user") or (message.role == "system" and not loop.first) %}
{{- '<|im_start|>' + message.role + '\n' + message.content + '<|im_end|>' + '\n' }}
{%- elif message.role == "assistant" and not message.tool_calls %}
{%- set content = message.content %}
{%- if not loop.last %}
{%- set content = message.content.split('</think>')[-1].lstrip('\n') %}
{%- endif %}
{{- '<|im_start|>' + message.role + '\n' + content + '<|im_end|>' + '\n' }}
{%- elif message.role == "assistant" %}
{%- set content = message.content %}
{%- if not loop.last %}
{%- set content = …
```
> fix Qwen/QwQ-32B
